# backend/db/models/analysis.py
"""Analysis session and agent report models."""
import uuid
from datetime import datetime
from typing import Optional, TYPE_CHECKING

from sqlalchemy import ForeignKey, String, Float, Boolean, Text, Enum as SQLEnum, JSON
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from backend.ai.state.enums import Market, AgentType, Action
from .base import Base

if TYPE_CHECKING:
    from .user import User


class AnalysisSession(Base):
    """A single analysis session for a ticker."""
    __tablename__ = "analysis_sessions"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    ticker: Mapped[str] = mapped_column(String(20))
    market: Mapped[Market] = mapped_column(SQLEnum(Market))
    created_at: Mapped[datetime] = mapped_column(default=datetime.now)
    completed_at: Mapped[Optional[datetime]] = mapped_column(nullable=True)
    user_id: Mapped[Optional[uuid.UUID]] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)

    # Relationships
    user: Mapped[Optional["User"]] = relationship(back_populates="analysis_sessions")
    agent_reports: Mapped[list["AgentReport"]] = relationship(back_populates="session", cascade="all, delete-orphan")
    final_decision: Mapped[Optional["FinalDecision"]] = relationship(back_populates="session", cascade="all, delete-orphan")


class AgentReport(Base):
    """Report generated by an individual agent."""
    __tablename__ = "agent_reports"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    session_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("analysis_sessions.id"))
    agent_type: Mapped[AgentType] = mapped_column(SQLEnum(AgentType))
    report_data: Mapped[dict] = mapped_column(JSON)
    created_at: Mapped[datetime] = mapped_column(default=datetime.now)

    # Relationships
    session: Mapped["AnalysisSession"] = relationship(back_populates="agent_reports")


class FinalDecision(Base):
    """Final trading decision for an analysis session."""
    __tablename__ = "final_decisions"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    session_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("analysis_sessions.id"), unique=True)
    action: Mapped[Action] = mapped_column(SQLEnum(Action))
    confidence: Mapped[float] = mapped_column(Float)
    rationale: Mapped[str] = mapped_column(Text)
    vetoed: Mapped[bool] = mapped_column(Boolean, default=False)
    veto_reason: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(default=datetime.now)

    # Relationships
    session: Mapped["AnalysisSession"] = relationship(back_populates="final_decision")
