"""add_performance_tracking_tables

Revision ID: 1e04e15e9cbb
Revises: 72cb97146dab
Create Date: 2026-02-09 08:59:47.358961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '1e04e15e9cbb'
down_revision: Union[str, Sequence[str], None] = '72cb97146dab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Use existing enum types created in initial migration
    agenttype_enum = postgresql.ENUM('FUNDAMENTAL', 'SENTIMENT', 'TECHNICAL', 'RISK', 'CHAIRPERSON', name='agenttype', create_type=False)
    action_enum = postgresql.ENUM('BUY', 'SELL', 'HOLD', name='action', create_type=False)
    market_enum = postgresql.ENUM('US', 'TASE', name='market', create_type=False)

    # Create new enum type for LLMProvider manually
    op.execute("CREATE TYPE llmprovider AS ENUM ('ANTHROPIC', 'OPENAI', 'GEMINI')")

    llmprovider_enum = postgresql.ENUM('ANTHROPIC', 'OPENAI', 'GEMINI', name='llmprovider', create_type=False)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_accuracy',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_type', agenttype_enum, nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('total_signals', sa.Integer(), nullable=False),
    sa.Column('correct_signals', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('last_calculated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('portfolios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', llmprovider_enum, nullable=False),
    sa.Column('encrypted_key', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_outcomes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('action_recommended', action_enum, nullable=False),
    sa.Column('price_at_recommendation', sa.Float(), nullable=False),
    sa.Column('price_after_1d', sa.Float(), nullable=True),
    sa.Column('price_after_7d', sa.Float(), nullable=True),
    sa.Column('price_after_30d', sa.Float(), nullable=True),
    sa.Column('price_after_90d', sa.Float(), nullable=True),
    sa.Column('outcome_correct', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['analysis_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('market', market_enum, nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('avg_entry_price', sa.Float(), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlist_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('watchlist_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('market', market_enum, nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('analysis_sessions', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'analysis_sessions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'analysis_sessions', type_='foreignkey')
    op.drop_column('analysis_sessions', 'user_id')
    op.drop_table('watchlist_items')
    op.drop_table('positions')
    op.drop_table('analysis_outcomes')
    op.drop_table('watchlists')
    op.drop_table('user_api_keys')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('agent_accuracy')
    # ### end Alembic commands ###
