"""add_user_and_portfolio_tables

Revision ID: 5f691480b773
Revises: 1e04e15e9cbb
Create Date: 2026-02-09 09:12:07.783108

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "5f691480b773"
down_revision: Union[str, Sequence[str], None] = "1e04e15e9cbb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
