"""remove_user_api_keys

Revision ID: d4e52e30ebd3
Revises: ab39d61d2eff
Create Date: 2026-02-17 20:50:19.580005

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d4e52e30ebd3"
down_revision: Union[str, Sequence[str], None] = "ab39d61d2eff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_api_keys")
    op.alter_column(
        "backtest_results", "strategy_id", existing_type=sa.UUID(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "backtest_results", "strategy_id", existing_type=sa.UUID(), nullable=True
    )
    op.create_table(
        "user_api_keys",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "provider",
            postgresql.ENUM("ANTHROPIC", "OPENAI", "GEMINI", name="llmprovider"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "encrypted_key", postgresql.BYTEA(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("user_api_keys_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("user_api_keys_pkey")),
    )
    # ### end Alembic commands ###
